"""initial schema

Revision ID: 6a95e09808be
Revises: 
Create Date: 2026-03-27 22:17:04.326934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a95e09808be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docentes', sa.Column('creado_por_id', sa.Integer(), nullable=True))
    op.add_column('docentes', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_foreign_key(None, 'docentes', 'provincias', ['provincia_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'docentes', 'docentes', ['creado_por_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'docentes', 'distritos', ['distrito_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docentes', type_='foreignkey')
    op.drop_constraint(None, 'docentes', type_='foreignkey')
    op.drop_constraint(None, 'docentes', type_='foreignkey')
    op.drop_column('docentes', 'fecha_creacion')
    op.drop_column('docentes', 'creado_por_id')
    # ### end Alembic commands ###
